"""TorchInferno: torch-native inference building blocks."""

from torchinferno.audit import FeatureAudit, TorchInfernoAudit, build_audit_report
from torchinferno.compiler import CompileConfig, compile_forward
from torchinferno.kernels import (
    NVFP4Tensor,
    dequantize_nvfp4,
    fused_rmsnorm_swiglu,
    fused_rmsnorm_swiglu_reference,
    nvfp4_linear_reference,
    paged_decode_attention,
    quantize_nvfp4,
)
from torchinferno.models.auto import load_model_auto
from torchinferno.models.conversion import (
    audit_deepseek_checkpoint,
    audit_native_deepseek_checkpoint,
    convert_deepseek_checkpoint,
    convert_native_deepseek_checkpoint,
)
from torchinferno.models.deepseek import DeepSeekV32Config, DeepSeekV32ForCausalLM, tiny_deepseek_v32_config
from torchinferno.models.dsv4 import DSv4Config, DSv4ForCausalLM, tiny_dsv4_config
from torchinferno.models.llama3_family import (
    LLAMA3_70B_REPO_ID,
    Llama3Config,
    Llama3PipelineForCausalLM,
    Llama3PipelineLoadReport,
    Llama3TensorParallelForCausalLM,
    Llama3TensorParallelLoadReport,
    Llama3V0ForCausalLM,
    Llama3V1ForCausalLM,
    llama3_70b_config,
    resolve_llama3_checkpoint,
    tiny_llama3_config,
)
from torchinferno.models.provenance import ModelVariantSpec
from torchinferno.models.variants import get_model_variant, list_model_variants, model_variant_lineage
from torchinferno.profiling import (
    FocusProfileArtifacts,
    OffloadProfileArtifacts,
    OffloadProfileConfig,
    PatternProfileArtifacts,
    PatternProfileConfig,
    ProfileRunArtifacts,
    ProfileRunConfig,
    RegionProfileConfig,
    SubgraphProfileArtifacts,
    SubgraphProfileConfig,
    TimeSliceProfileArtifacts,
    TimeSliceProfileConfig,
    run_offload_profile_capture,
    run_pattern_profile_capture,
    run_profile_capture,
    run_region_profile_capture,
    run_subgraph_profile_capture,
    run_timeslice_profile_capture,
)
from torchinferno.tokenization import load_text_tokenizer
from torchinferno.validation import (
    LogitReference,
    ValidationResult,
    capture_logit_reference,
    load_logit_reference,
    save_logit_reference,
    validate_logit_reference,
)
from torchinferno.variant_validation import (
    SkippedVariantComparison,
    VariantLogitComparison,
    VariantLogitValidationReport,
    run_variant_logit_validation,
    save_variant_logit_report,
)

__all__ = [
    "CompileConfig",
    "DSv4Config",
    "DSv4ForCausalLM",
    "DeepSeekV32Config",
    "DeepSeekV32ForCausalLM",
    "FeatureAudit",
    "FocusProfileArtifacts",
    "LogitReference",
    "LLAMA3_70B_REPO_ID",
    "Llama3Config",
    "Llama3PipelineForCausalLM",
    "Llama3PipelineLoadReport",
    "Llama3TensorParallelForCausalLM",
    "Llama3TensorParallelLoadReport",
    "Llama3V0ForCausalLM",
    "Llama3V1ForCausalLM",
    "ModelVariantSpec",
    "NVFP4Tensor",
    "OffloadProfileArtifacts",
    "OffloadProfileConfig",
    "PatternProfileArtifacts",
    "PatternProfileConfig",
    "ProfileRunArtifacts",
    "ProfileRunConfig",
    "RegionProfileConfig",
    "SkippedVariantComparison",
    "SubgraphProfileArtifacts",
    "SubgraphProfileConfig",
    "TimeSliceProfileArtifacts",
    "TimeSliceProfileConfig",
    "TorchInfernoAudit",
    "ValidationResult",
    "VariantLogitComparison",
    "VariantLogitValidationReport",
    "audit_deepseek_checkpoint",
    "audit_native_deepseek_checkpoint",
    "build_audit_report",
    "capture_logit_reference",
    "compile_forward",
    "convert_deepseek_checkpoint",
    "convert_native_deepseek_checkpoint",
    "dequantize_nvfp4",
    "fused_rmsnorm_swiglu",
    "fused_rmsnorm_swiglu_reference",
    "load_logit_reference",
    "load_model_auto",
    "load_text_tokenizer",
    "llama3_70b_config",
    "get_model_variant",
    "list_model_variants",
    "model_variant_lineage",
    "nvfp4_linear_reference",
    "paged_decode_attention",
    "quantize_nvfp4",
    "resolve_llama3_checkpoint",
    "run_pattern_profile_capture",
    "run_offload_profile_capture",
    "run_profile_capture",
    "run_region_profile_capture",
    "run_subgraph_profile_capture",
    "run_timeslice_profile_capture",
    "run_variant_logit_validation",
    "save_logit_reference",
    "save_variant_logit_report",
    "tiny_deepseek_v32_config",
    "tiny_dsv4_config",
    "tiny_llama3_config",
    "validate_logit_reference",
]
